[package]
name = "xiangqi-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "fat"

[dependencies]
rand = "0.9.0-alpha.2"
tungstenite = {version =  "0.24.0", features = ["native-tls"] }
serde_json = "1.0"
serde = { version = "1.0.214", features = ["derive"] }
fnv = "1.0.7"